import { GestionPlazaInterface } from '@models/gestion-plaza.interface';

export const DUMMIE_TABLA_GESTION_PLAZAS: GestionPlazaInterface[] = [
  {
    id: 1,
    ooad: 'CDMX Norte',
    noPlaza: '0012345',
    tipoUnidad: 'Ordinaria',
    categoria: 'Médico especialista',
    especialidad: 'Pediatría',
    horario: '07:00 - 14:00',
    turno: 'Matutino',
    zona: 'Zona 1',
    marcaOcupacion: 'Vacante',
    clasificacionUnidad: 'Hospital general',
    unidad: 'Unidad médica de alta especialidad',
    adscripcion: 'Hospital general de zona  No. 17',
    tipoPlaza: 'Base',
    estatus: 'Vacante'
  },
  {
    id: 2,
    ooad: 'CDMX Norte',
    noPlaza: '3112851',
    tipoUnidad: 'Ordinaria',
    categoria: 'Médico especialista',
    especialidad: 'Pediatría',
    horario: '14:00 - 21:00',
    turno: 'Vespertino',
    zona: 'Zona 3',
    marcaOcupacion: 'Ocupada',
    clasificacionUnidad: 'Hospital general',
    unidad: 'Unidad médica de alta especialidad',
    adscripcion: 'Hospital general de zona  No. 17',
    tipoPlaza: 'Confianza',
    estatus: 'Etiquetada'
  },
  {
    id: 3,
    ooad: 'CDMX Norte',
    noPlaza: '3110894',
    tipoUnidad: 'Ordinaria',
    categoria: 'Médico especialista',
    especialidad: 'Traumatología',
    horario: '21:00 - 07:00',
    turno: 'Nocturno',
    zona: 'Zona 2',
    marcaOcupacion: 'Vacante',
    clasificacionUnidad: 'Hospital general',
    unidad: 'Unidad médica de alta especialidad',
    adscripcion: 'Unidad de medicina familiar No.45',
    tipoPlaza: 'Base',
    estatus: 'Vacante'
  },
  {
    id: 4,
    ooad: 'CDMX Norte',
    noPlaza: '3114865',
    tipoUnidad: 'IMSS Bienestar',
    categoria: 'Médico especialista',
    especialidad: 'Ginecología',
    horario: '07:00 - 14:00',
    turno: 'Matutino',
    zona: 'Zona 3',
    marcaOcupacion: 'Ocupada',
    clasificacionUnidad: 'Hospital regional',
    unidad: 'Unidad médica de alta especialidad',
    adscripcion: 'Hospital general regional No.25',
    tipoPlaza: 'Eventual',
    estatus: 'Etiquetada'
  },
  {
    id: 5,
    ooad: 'CDMX Norte',
    noPlaza: '3115648',
    tipoUnidad: 'IMSS Bienestar',
    categoria: 'Médico especialista',
    especialidad: 'Pediatría',
    horario: '07:00 - 14:00',
    turno: 'Matutino',
    zona: 'Zona 7',
    marcaOcupacion: 'Temporal',
    clasificacionUnidad: 'Hospital general',
    unidad: 'Unidad médica de alta especialidad',
    adscripcion: 'Hospital general de zona  No. 17',
    tipoPlaza: 'Confianza',
    estatus: 'Etiquetada'
  },
  {
    id: 6,
    ooad: 'CDMX Norte',
    noPlaza: '3115265',
    tipoUnidad: 'Ordinaria',
    categoria: 'Médico especialista',
    especialidad: 'Traumatología',
    horario: '15:00 - 23:00',
    turno: 'Jornada acumulada',
    zona: 'Zona 1',
    marcaOcupacion: 'Sustitución',
    clasificacionUnidad: 'Hospital general',
    unidad: 'Unidad médica de alta especialidad',
    adscripcion: 'Hospital general de zona  No. 17',
    tipoPlaza: 'Base',
    estatus: 'Etiquetada'
  },
  {
    id: 7,
    ooad: 'CDMX Norte',
    noPlaza: '3118564',
    tipoUnidad: 'Ordinaria',
    categoria: 'Médico especialista',
    especialidad: 'Pediatría',
    horario: '21:00 - 07:00',
    turno: 'Nocturno',
    zona: 'Zona 8',
    marcaOcupacion: 'Residencia',
    clasificacionUnidad: 'Hospital general',
    unidad: 'Unidad médica de alta especialidad',
    adscripcion: 'Unidad de medicina familiar No.45',
    tipoPlaza: 'Confianza',
    estatus: 'Etiquetada'
  },
  {
    id: 8,
    ooad: 'CDMX Norte',
    noPlaza: '3118465',
    tipoUnidad: 'IMSS Bienestar',
    categoria: 'Médico especialista',
    especialidad: 'Cardiología',
    horario: '15:00 - 23:00',
    turno: 'Jornada acumulada',
    zona: 'Zona 4',
    marcaOcupacion: 'Ocupada',
    clasificacionUnidad: 'Hospital general',
    unidad: 'Unidad médica de alta especialidad',
    adscripcion: 'Hospital general de zona  No. 17',
    tipoPlaza: 'Eventual',
    estatus: 'Etiquetada'
  },
  {
    id: 9,
    ooad: 'CDMX Norte',
    noPlaza: '3114589',
    tipoUnidad: 'Ordinaria',
    categoria: 'Médico especialista',
    especialidad: 'Ginecología',
    horario: '15:00 - 23:00',
    turno: 'Jornada acumulada',
    zona: 'Zona 1',
    marcaOcupacion: 'Vacante',
    clasificacionUnidad: 'Hospital general',
    unidad: 'Unidad médica de alta especialidad',
    adscripcion: 'Hospital general de zona  No. 17',
    tipoPlaza: 'Base',
    estatus: 'Vacante'
  },
  {
    id: 10,
    ooad: 'CDMX Norte',
    noPlaza: '3110948',
    tipoUnidad: 'IMSS Bienestar',
    categoria: 'Médico especialista',
    especialidad: 'Pediatría',
    horario: '21:00 - 07:00',
    turno: 'Nocturno',
    zona: 'Zona 6',
    marcaOcupacion: 'Temporal',
    clasificacionUnidad: 'Hospital general',
    unidad: 'Unidad médica de alta especialidad',
    adscripcion: 'Hospital general de zona  No. 17',
    tipoPlaza: 'Eventual',
    estatus: 'Etiquetada'
  },
  {
    id: 11,
    ooad: 'CDMX Norte',
    noPlaza: '3119940',
    tipoUnidad: 'Ordinaria',
    categoria: 'Médico especialista',
    especialidad: 'Medicina Interna',
    horario: '07:00 - 14:00',
    turno: 'Matutino',
    zona: 'Zona 5',
    marcaOcupacion: 'Ocupada',
    clasificacionUnidad: 'Hospital general',
    unidad: 'Unidad médica de alta especialidad',
    adscripcion: 'Hospital general de zona  No. 17',
    tipoPlaza: 'Base',
    estatus: 'Ocupada'
  }
];
