export interface UsuarioAsistencia {
  idParticipante: number,
  nomParticipante: string,
  uuidArchivo: string,
  matricula: string | null,
  curp: string,
  rfc: string,
  fechaCita: string,
  horaCita: string,
  mesaCita: string,
  turnoCita: string,
  diaAsistenciaCita: string,
  horaAsistencia: string,
  turnoAsistencia: string,
  modalidad: string,
  estatus: string,
  verificacionDoc: string,
  especialidades: string[],
  indCitaExtraordinaria: boolean,
}
