export const NAV = {
  publico: 'publico/',
  privado: 'privado/',
  inicioSesion: 'inicio-sesion',
  crearCuenta: 'crear-cuenta',
  registroMedico: 'registro-medico',
  recuperarContrasenia: 'recuperar-contrasenia',
  nuevaContrasenia: 'restablecer-contrasenia',
  documentacionAspirante: 'documentacion-aspirante/:id',
  verificacionDocumentos: 'verificacion-documentos',
  ofertaLaboral: 'oferta-laboral',
  asignacion: 'asignacion',
  cargaCalificaciones: 'carga-calificaciones',
  asistenciaExtraordinaria: 'asistencia-extraordinaria',
  home: 'inicio',
};
