export const NAV = {
  publico: 'publico/',
  privado: 'privado/',
  inicioSesion: 'inicio-sesion',
  crearCuenta: 'crear-cuenta',
  registroMedico: 'registro-medico',
  recuperarContrasenia: 'recuperar-contrasenia',
  nuevaContrasenia: 'restablecer-contrasenia',
  documentacionAspirante: 'documentacion-aspirante/:id',
  verificacionDocumentos: 'verificacion-documentos',
  ofertaLaboral: 'oferta-laboral',
  asignacion: 'asignacion-plaza',
  cargaCalificaciones: 'carga-calificaciones',
  asistenciaExtraordinaria: 'asistencia-extraordinaria',
  visualizacionAsistencia: 'visualizacion-asistencia',
  tableroInformacionAsistencia: 'tablero-asistencia',
  asignacionMesa: 'asignacion-mesa',
  propuestaSindical: 'propuesta-sindical',
  gestionConvocatoria: 'gestion-convocatoria',
  monitoreoAsignaciones: 'monitoreo-asignaciones',
  errorConfig: 'config-erronea',
  home: 'inicio',
  homeModulos: 'inicio-modulos',
};
